{"uuid": "a8a88153-9948-48ab-8877-9b8939f368d9", "children": ["207c21d9-6596-4f57-8a84-33bfa0f1fc9a", "15a66f24-65e4-4b8c-bd00-1c6423abcae6", "1a712e14-d501-4665-8333-efa9932ef863", "91b9e7d7-a075-4b11-b58c-440c9d0e3b8d", "7718d8f3-405c-46cc-b888-9e1f75a45202", "a831c493-55d6-4e6c-a4ee-a0311d909bcd"], "befores": [{"name": "setup_profiles", "status": "broken", "statusDetails": {"message": "requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))\n", "trace": "  File \"/usr/local/lib/python3.8/site-packages/pluggy/callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"/usr/local/lib/python3.8/site-packages/_pytest/fixtures.py\", line 1126, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/usr/local/lib/python3.8/site-packages/_pytest/fixtures.py\", line 925, in call_fixture_func\n    fixture_result = next(generator)\n  File \"/wlan-testing/tests/e2e/basic/conftest.py\", line 79, in setup_profiles\n    return_var = fixtures_ver.setup_profiles(request, param, setup_controller, testbed, get_equipment_id,\n  File \"/wlan-testing/tests/fixtures_2x.py\", line 243, in setup_profiles\n    instantiate_profile_obj.push_config(serial_number=get_equipment_id[0])\n  File \"/wlan-testing/tests/../libs/controller/controller_2x/controller.py\", line 423, in push_config\n    resp = requests.post(uri, data=basic_cfg_str, headers=self.sdk_client.make_headers(),\n  File \"/usr/local/lib/python3.8/site-packages/requests/api.py\", line 117, in post\n    return request('post', url, data=data, json=json, **kwargs)\n  File \"/usr/local/lib/python3.8/site-packages/requests/api.py\", line 61, in request\n    return session.request(method=method, url=url, **kwargs)\n  File \"/usr/local/lib/python3.8/site-packages/requests/sessions.py\", line 542, in request\n    resp = self.send(prep, **send_kwargs)\n  File \"/usr/local/lib/python3.8/site-packages/requests/sessions.py\", line 655, in send\n    r = adapter.send(request, **kwargs)\n  File \"/usr/local/lib/python3.8/site-packages/requests/adapters.py\", line 498, in send\n    raise ConnectionError(err, request=request)\n"}, "attachments": [{"name": "ucentral_config: ", "source": "7f0ef3f0-07f6-4b5e-855c-4d4d90f3174e-attachment.attach"}], "start": 1631406466716, "stop": 1631406499090}], "start": 1631406466716, "stop": 1631406506441}