{"uuid": "cd2b45bc-9ddc-4dae-b70c-c47ce6d38026", "children": ["5dc46188-b350-494f-9d5b-bcc22d2db5c8", "c1d7cdae-c4db-455b-9462-011b0f884406", "981e0a03-2e3c-4189-a17a-8fc4cb054006", "c39b2abc-1f4e-4238-a15d-2b44dd385f3c", "d26c9494-2201-46f7-8887-759106f4f4c5", "0e5f0d44-786e-444c-9d4c-e35442c7f2e8"], "befores": [{"name": "setup_profiles", "status": "broken", "statusDetails": {"message": "requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))\n", "trace": "  File \"/usr/local/lib/python3.8/site-packages/pluggy/callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"/usr/local/lib/python3.8/site-packages/_pytest/fixtures.py\", line 1126, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/usr/local/lib/python3.8/site-packages/_pytest/fixtures.py\", line 925, in call_fixture_func\n    fixture_result = next(generator)\n  File \"/wlan-testing/tests/e2e/basic/conftest.py\", line 79, in setup_profiles\n    return_var = fixtures_ver.setup_profiles(request, param, setup_controller, testbed, get_equipment_id,\n  File \"/wlan-testing/tests/fixtures_2x.py\", line 243, in setup_profiles\n    instantiate_profile_obj.push_config(serial_number=get_equipment_id[0])\n  File \"/wlan-testing/tests/../libs/controller/controller_2x/controller.py\", line 423, in push_config\n    resp = requests.post(uri, data=basic_cfg_str, headers=self.sdk_client.make_headers(),\n  File \"/usr/local/lib/python3.8/site-packages/requests/api.py\", line 117, in post\n    return request('post', url, data=data, json=json, **kwargs)\n  File \"/usr/local/lib/python3.8/site-packages/requests/api.py\", line 61, in request\n    return session.request(method=method, url=url, **kwargs)\n  File \"/usr/local/lib/python3.8/site-packages/requests/sessions.py\", line 542, in request\n    resp = self.send(prep, **send_kwargs)\n  File \"/usr/local/lib/python3.8/site-packages/requests/sessions.py\", line 655, in send\n    r = adapter.send(request, **kwargs)\n  File \"/usr/local/lib/python3.8/site-packages/requests/adapters.py\", line 498, in send\n    raise ConnectionError(err, request=request)\n"}, "attachments": [{"name": "ucentral_config: ", "source": "e52fb63e-2315-4b93-a8b3-53654bea5102-attachment.attach"}], "start": 1631406320285, "stop": 1631406351639}], "start": 1631406320285, "stop": 1631406358645}