{"uuid": "87158c8e-2894-4c41-aad4-c5614748f714", "children": ["1fb5a3c0-d879-433e-a5be-a9ee5d7a4c52", "08aedade-604d-45a7-a4bf-09e2a5268fc0"], "befores": [{"name": "setup_profiles", "status": "broken", "statusDetails": {"message": "socket.timeout: timed out\n", "trace": "  File \"/usr/local/lib/python3.8/site-packages/pluggy/callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"/usr/local/lib/python3.8/site-packages/_pytest/fixtures.py\", line 1126, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/usr/local/lib/python3.8/site-packages/_pytest/fixtures.py\", line 925, in call_fixture_func\n    fixture_result = next(generator)\n  File \"/wlan-testing/tests/e2e/basic/conftest.py\", line 752, in setup_profiles\n    ap_ssh = get_apnos(get_configuration['access_point'][0], pwd=\"../libs/apnos/\", sdk=\"2.x\")\n  File \"/wlan-testing/tests/../libs/apnos/apnos.py\", line 39, in __init__\n    client = self.ssh_cli_connect()\n  File \"/wlan-testing/tests/../libs/apnos/apnos.py\", line 70, in ssh_cli_connect\n    client.connect(self.ip, username=self.username, password=self.password,\n  File \"/usr/local/lib/python3.8/site-packages/paramiko/client.py\", line 349, in connect\n    retry_on_signal(lambda: sock.connect(addr))\n  File \"/usr/local/lib/python3.8/site-packages/paramiko/util.py\", line 283, in retry_on_signal\n    return function()\n  File \"/usr/local/lib/python3.8/site-packages/paramiko/client.py\", line 349, in <lambda>\n    retry_on_signal(lambda: sock.connect(addr))\n"}, "attachments": [{"name": "SSID Profile Created", "source": "26c01d74-3b58-481c-8d7c-7319e91d6c60-attachment.attach"}, {"name": "SSID Profile Created", "source": "018b3de5-0666-4285-85de-7b02696280db-attachment.attach"}, {"name": "APNOS LIbrary: ", "source": "2552b528-2273-4ac1-9160-433cac709a29-attachment.attach"}], "start": 1627627237693, "stop": 1627627247704}], "start": 1627627237693, "stop": 1627627248049}