{"uuid": "5d16e4b9-1b3d-4056-bb6b-afbe5e4c414e", "children": ["3b142d7e-b44d-4e76-aec7-06db4f1696c4", "7c7640a8-637d-4500-a522-fb0c656f9340", "d626d7f6-21ea-4307-9716-de4d9cc1e3ff", "2d2ca0d5-e046-4e06-8a44-728438ed0fd8", "acab9cec-596e-4bbe-9d43-5d9422616779", "247ec336-1232-4527-abaf-11d7a6587189"], "befores": [{"name": "setup_profiles", "status": "broken", "statusDetails": {"message": "requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))\n", "trace": "  File \"/usr/local/lib/python3.8/site-packages/pluggy/callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"/usr/local/lib/python3.8/site-packages/_pytest/fixtures.py\", line 1126, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/usr/local/lib/python3.8/site-packages/_pytest/fixtures.py\", line 925, in call_fixture_func\n    fixture_result = next(generator)\n  File \"/wlan-testing/tests/e2e/interOp/conftest.py\", line 226, in setup_profiles\n    return_var = fixtures_ver.setup_profiles(request, param, setup_controller, testbed, get_equipment_id,\n  File \"/wlan-testing/tests/fixtures_2x.py\", line 243, in setup_profiles\n    instantiate_profile_obj.push_config(serial_number=get_equipment_id[0])\n  File \"/wlan-testing/tests/../libs/controller/controller_2x/controller.py\", line 423, in push_config\n    resp = requests.post(uri, data=basic_cfg_str, headers=self.sdk_client.make_headers(),\n  File \"/usr/local/lib/python3.8/site-packages/requests/api.py\", line 117, in post\n    return request('post', url, data=data, json=json, **kwargs)\n  File \"/usr/local/lib/python3.8/site-packages/requests/api.py\", line 61, in request\n    return session.request(method=method, url=url, **kwargs)\n  File \"/usr/local/lib/python3.8/site-packages/requests/sessions.py\", line 542, in request\n    resp = self.send(prep, **send_kwargs)\n  File \"/usr/local/lib/python3.8/site-packages/requests/sessions.py\", line 655, in send\n    r = adapter.send(request, **kwargs)\n  File \"/usr/local/lib/python3.8/site-packages/requests/adapters.py\", line 498, in send\n    raise ConnectionError(err, request=request)\n"}, "attachments": [{"name": "ucentral_config: ", "source": "ed0c1ba8-2848-4645-aa15-1722ceac4bb8-attachment.attach"}], "start": 1631406781693, "stop": 1631406812744}], "start": 1631406781693, "stop": 1631406816409}