{"uuid": "e8d47eea-50a1-4bbd-9f06-95a24eb9aec8", "children": ["a631486a-d9f4-4e40-8d69-208d13ee7f5c", "ccdc7800-0b4b-4097-86e2-bbbba2f2b429", "63b22a9d-cfb9-4cba-accc-2fc456b44661", "41519244-bdae-4b56-a347-f6f07fe38742", "b8dca9c9-e550-44fa-974c-4d0f7267f161", "dc6346e6-b621-43ed-93d9-96762fc4e81c"], "befores": [{"name": "setup_profiles", "status": "broken", "statusDetails": {"message": "swagger_client.rest.ApiException: (502)\nReason: Bad Gateway\nHTTP response headers: HTTPHeaderDict({'Server': 'awselb/2.0', 'Date': 'Thu, 19 Aug 2021 02:56:15 GMT', 'Content-Type': 'text/html', 'Content-Length': '122', 'Connection': 'keep-alive'})\nHTTP response body: <html>\r\n<head><title>502 Bad Gateway</title></head>\r\n<body>\r\n<center><h1>502 Bad Gateway</h1></center>\r\n</body>\r\n</html>\r\n\n\n", "trace": "  File \"/usr/local/lib/python3.8/site-packages/pluggy/callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"/usr/local/lib/python3.8/site-packages/_pytest/fixtures.py\", line 1126, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/usr/local/lib/python3.8/site-packages/_pytest/fixtures.py\", line 925, in call_fixture_func\n    fixture_result = next(generator)\n  File \"/wlan-testing/tests/e2e/basic/conftest.py\", line 79, in setup_profiles\n    return_var = fixtures_ver.setup_profiles(request, param, setup_controller, testbed, get_equipment_id,\n  File \"/wlan-testing/tests/fixtures_1x.py\", line 96, in setup_profiles\n    instantiate_profile.delete_profile_by_name(profile_name=testbed + \"-Equipment-AP-\" + parameter['mode'])\n  File \"/wlan-testing/tests/../libs/controller/controller_1x/controller.py\", line 432, in delete_profile_by_name\n    all_profiles = self.profile_client.get_profiles_by_customer_id(customer_id=self.sdk_client.customer_id,\n  File \"/usr/local/lib/python3.8/site-packages/swagger_client/api/profile_api.py\", line 527, in get_profiles_by_customer_id\n    (data) = self.get_profiles_by_customer_id_with_http_info(customer_id, pagination_context, **kwargs)  # noqa: E501\n  File \"/usr/local/lib/python3.8/site-packages/swagger_client/api/profile_api.py\", line 603, in get_profiles_by_customer_id_with_http_info\n    return self.api_client.call_api(\n  File \"/usr/local/lib/python3.8/site-packages/swagger_client/api_client.py\", line 316, in call_api\n    return self.__call_api(resource_path, method,\n  File \"/usr/local/lib/python3.8/site-packages/swagger_client/api_client.py\", line 148, in __call_api\n    response_data = self.request(\n  File \"/usr/local/lib/python3.8/site-packages/swagger_client/api_client.py\", line 338, in request\n    return self.rest_client.GET(url,\n  File \"/usr/local/lib/python3.8/site-packages/swagger_client/rest.py\", line 233, in GET\n    return self.request(\"GET\", url,\n  File \"/usr/local/lib/python3.8/site-packages/swagger_client/rest.py\", line 227, in request\n    raise ApiException(http_resp=r)\n"}, "start": 1629341767507, "stop": 1629341775369}], "start": 1629341767507, "stop": 1629341776354}