{"uuid": "2ae88260-ce7d-4d1d-8b80-993f291debc9", "children": ["18086fe2-6237-463e-9f12-2b26486b8adf", "999a0399-1c92-40ff-bc10-23cef78f7c3e", "238fe47b-a23f-4038-8e5b-3e6c3a3f8610", "4fcc5710-af04-44cd-b9c4-223361639696", "b179814d-e514-4516-9ea6-c5ec24390703", "ff3a3222-5e15-486d-a920-a4611e99d881"], "befores": [{"name": "setup_profiles", "status": "broken", "statusDetails": {"message": "swagger_client.rest.ApiException: (401)\nReason: \nHTTP response headers: HTTPHeaderDict({'Date': 'Thu, 19 Aug 2021 02:57:14 GMT', 'Content-Length': '74', 'Connection': 'keep-alive', 'Access-Control-Allow-Origin': '*', 'Access-Control-Allow-Methods': 'POST, PATCH, PUT, HEAD, GET, OPTIONS, DELETE', 'Access-Control-Max-Age': '10', 'Access-Control-Allow-Headers': 'x-requested-with,Content-Type,content-type,Authorization', 'Access-Control-Allow-Credentials': 'true', 'X-Content-Type-Options': 'nosniff', 'X-XSS-Protection': '1; mode=block', 'Strict-Transport-Security': 'max-age=31536000 ; includeSubDomains', 'X-Frame-Options': 'DENY', 'Cache-Control': 'no-cache, no-store, max-age=0, must-revalidate', 'Expires': '0', 'Pragma': 'no-cache'})\nHTTP response body: HTTP Status 401 - Full authentication is required to access this resource\n\n\n", "trace": "  File \"/usr/local/lib/python3.8/site-packages/pluggy/callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"/usr/local/lib/python3.8/site-packages/_pytest/fixtures.py\", line 1126, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/usr/local/lib/python3.8/site-packages/_pytest/fixtures.py\", line 925, in call_fixture_func\n    fixture_result = next(generator)\n  File \"/wlan-testing/tests/e2e/basic/conftest.py\", line 79, in setup_profiles\n    return_var = fixtures_ver.setup_profiles(request, param, setup_controller, testbed, get_equipment_id,\n  File \"/wlan-testing/tests/fixtures_1x.py\", line 96, in setup_profiles\n    instantiate_profile.delete_profile_by_name(profile_name=testbed + \"-Equipment-AP-\" + parameter['mode'])\n  File \"/wlan-testing/tests/../libs/controller/controller_1x/controller.py\", line 432, in delete_profile_by_name\n    all_profiles = self.profile_client.get_profiles_by_customer_id(customer_id=self.sdk_client.customer_id,\n  File \"/usr/local/lib/python3.8/site-packages/swagger_client/api/profile_api.py\", line 527, in get_profiles_by_customer_id\n    (data) = self.get_profiles_by_customer_id_with_http_info(customer_id, pagination_context, **kwargs)  # noqa: E501\n  File \"/usr/local/lib/python3.8/site-packages/swagger_client/api/profile_api.py\", line 603, in get_profiles_by_customer_id_with_http_info\n    return self.api_client.call_api(\n  File \"/usr/local/lib/python3.8/site-packages/swagger_client/api_client.py\", line 316, in call_api\n    return self.__call_api(resource_path, method,\n  File \"/usr/local/lib/python3.8/site-packages/swagger_client/api_client.py\", line 148, in __call_api\n    response_data = self.request(\n  File \"/usr/local/lib/python3.8/site-packages/swagger_client/api_client.py\", line 338, in request\n    return self.rest_client.GET(url,\n  File \"/usr/local/lib/python3.8/site-packages/swagger_client/rest.py\", line 233, in GET\n    return self.request(\"GET\", url,\n  File \"/usr/local/lib/python3.8/site-packages/swagger_client/rest.py\", line 227, in request\n    raise ApiException(http_resp=r)\n"}, "start": 1629341816977, "stop": 1629341834280}], "start": 1629341816977, "stop": 1629341835316}