{"uuid": "3f6a00b7-4b38-4c3d-b058-eb6e178b618a", "children": ["aafec6d0-c7c6-4dae-9080-a0494ef352a0", "8aa4ecab-d5bf-4bf2-8d86-a1c46451527f", "37ccc0c1-e1d2-432e-bbb2-a839357a465c", "2d16c7df-7a8d-4baf-8fbd-3e516d002cf8", "29b10cad-e156-47d8-9c8b-8a26bd1a9340", "128adcd4-e2bf-479b-aa3b-96dcdca95f1b"], "befores": [{"name": "setup_profiles", "status": "broken", "statusDetails": {"message": "requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))\n", "trace": "  File \"/usr/local/lib/python3.8/site-packages/pluggy/callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"/usr/local/lib/python3.8/site-packages/_pytest/fixtures.py\", line 1126, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/usr/local/lib/python3.8/site-packages/_pytest/fixtures.py\", line 925, in call_fixture_func\n    fixture_result = next(generator)\n  File \"/wlan-testing/tests/e2e/basic/conftest.py\", line 79, in setup_profiles\n    return_var = fixtures_ver.setup_profiles(request, param, setup_controller, testbed, get_equipment_id,\n  File \"/wlan-testing/tests/fixtures_2x.py\", line 243, in setup_profiles\n    instantiate_profile_obj.push_config(serial_number=get_equipment_id[0])\n  File \"/wlan-testing/tests/../libs/controller/controller_2x/controller.py\", line 423, in push_config\n    resp = requests.post(uri, data=basic_cfg_str, headers=self.sdk_client.make_headers(),\n  File \"/usr/local/lib/python3.8/site-packages/requests/api.py\", line 117, in post\n    return request('post', url, data=data, json=json, **kwargs)\n  File \"/usr/local/lib/python3.8/site-packages/requests/api.py\", line 61, in request\n    return session.request(method=method, url=url, **kwargs)\n  File \"/usr/local/lib/python3.8/site-packages/requests/sessions.py\", line 542, in request\n    resp = self.send(prep, **send_kwargs)\n  File \"/usr/local/lib/python3.8/site-packages/requests/sessions.py\", line 655, in send\n    r = adapter.send(request, **kwargs)\n  File \"/usr/local/lib/python3.8/site-packages/requests/adapters.py\", line 498, in send\n    raise ConnectionError(err, request=request)\n"}, "attachments": [{"name": "ucentral_config: ", "source": "f6125982-41db-4338-951f-1ed456f1e82d-attachment.attach"}], "start": 1631406598476, "stop": 1631406656800}], "start": 1631406598476, "stop": 1631406659779}