{"uuid": "c5528d23-c6cc-421a-9916-1eab2a562fc8", "children": ["ee6044ab-8bf5-4c52-99cc-3220305700ac", "05a5bedc-8d93-4738-9665-dc1fca1265b9", "c3ea31ef-72f7-44bb-9a8a-6dc07eefee41", "184a0475-4b58-481b-af83-a7ee0a6c788e", "ebf13ff7-527e-4434-a266-1abd629e43bb", "55f475a1-5ad9-4973-87e1-946e215ce7f3"], "befores": [{"name": "setup_profiles", "status": "broken", "statusDetails": {"message": "requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))\n", "trace": "  File \"/usr/local/lib/python3.8/site-packages/pluggy/callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"/usr/local/lib/python3.8/site-packages/_pytest/fixtures.py\", line 1126, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/usr/local/lib/python3.8/site-packages/_pytest/fixtures.py\", line 925, in call_fixture_func\n    fixture_result = next(generator)\n  File \"/wlan-testing/tests/e2e/basic/conftest.py\", line 79, in setup_profiles\n    return_var = fixtures_ver.setup_profiles(request, param, setup_controller, testbed, get_equipment_id,\n  File \"/wlan-testing/tests/fixtures_2x.py\", line 243, in setup_profiles\n    instantiate_profile_obj.push_config(serial_number=get_equipment_id[0])\n  File \"/wlan-testing/tests/../libs/controller/controller_2x/controller.py\", line 423, in push_config\n    resp = requests.post(uri, data=basic_cfg_str, headers=self.sdk_client.make_headers(),\n  File \"/usr/local/lib/python3.8/site-packages/requests/api.py\", line 117, in post\n    return request('post', url, data=data, json=json, **kwargs)\n  File \"/usr/local/lib/python3.8/site-packages/requests/api.py\", line 61, in request\n    return session.request(method=method, url=url, **kwargs)\n  File \"/usr/local/lib/python3.8/site-packages/requests/sessions.py\", line 542, in request\n    resp = self.send(prep, **send_kwargs)\n  File \"/usr/local/lib/python3.8/site-packages/requests/sessions.py\", line 655, in send\n    r = adapter.send(request, **kwargs)\n  File \"/usr/local/lib/python3.8/site-packages/requests/adapters.py\", line 498, in send\n    raise ConnectionError(err, request=request)\n"}, "attachments": [{"name": "ucentral_config: ", "source": "e6b85b02-1b76-4e92-8aab-639bcd4c595f-attachment.attach"}], "start": 1631406429136, "stop": 1631406461509}], "start": 1631406429136, "stop": 1631406466913}